---
title: "Transparent referencing of third-party work"
format: html
tbl-cap-location: top
fig-cap-location: bottom
---

::::: learning
::: learning-header
**Learning Outcome**
:::

::: learning-body
-   Students know how to transparently acknowledge knowledge from third parties in their work, by correctly and coherently using a reference system and a citation style
:::
:::::

## Introduction

New scientific findings do not emerge in an empty space. Rather, they build on ongoing scientific and social debates, they are based on existing knowledge and relate the new findings to previous scientific research and debates. This process of knowledge production usually culminates in the **communication of the new findings**. This can take various forms, for example in written student papers, scientific papers, books or scientific lectures aimed at a scientific audience. Alternatively, formats are chosen that appeal more to a non-scientific audience, for example blog posts, newspaper articles, presentations at relevant events, etc.

## Referring to third party work

Regardless of which format is chosen, a scientific research procedure is characterized (and differentiated from a non-scientific approach) by the fact that it is shown in a transparent and comprehensible way, which existing knowledge of third parties is referred to. This means that it must be **clearly recognizable which statements are your own and which statements have been taken from others**, as well as where they can be found. If this is not done, one speaks of plagiarism. **Plagiarism** is the stealing of other’s work without appropriately crediting or acknowledging the source and is considered misconducting scientific practice [@zabed_qi_2022]. Referring to sources not only acknowledges the knowledge of others, it also makes your own contribution more comprehensible and more substantial.

In their introductory work, @zabed_qi_2022 [p.493] give numerous examples of **when a reference is required**:

-   When describing or discussing a definition, theory, model, concept, or practice associated with a particular writer
    -   e.g., “Referencing can be defined as the acknowledgement of the works or ideas of other persons, which have been published formally or are available in the public domain in another way” (Reference).
-   To demonstrate the importance of the work
    -   e.g., “It has been reported that environmental conditions significantly affect the growth of a crop during field experiment” (Reference).
-   To point out a research gap in the report
    -   e.g., “In a recent study, it has been pointed out that still there is no scientific data on how the migrant workers can contribute to the social stability of the country” (Reference).
-   To show the vastness of the research work on the specific topic of the writer
    -   e.g., “Numerous studies have been done over the last several decades to improve technical and technological aspects of energy production” (Reference-1; Reference-2; Reference-3 and so on).
-   To describe the method(s) used in the study
    -   e.g., “Starch content in the rice flour was determined by the enzymatic method” (Reference).
-   To mention the source of data used in the research/report
    -   e.g., “Data present in this report on weather conditions during the experiment were obtained from the Ministry of Science and Technology, Malaysia” (Reference).
-   To identify the source of a material or equipment used during an experiment
    -   e.g., “The constructs used in this study were drawn from recent research” (Reference)
-   To show the similarity of the research outcome(s) to others’ work
    -   e.g., “In our investigation, it was observed that organizational performance decreased significantly with the decrease in workforce diversity. Similar findings have been reported elsewhere” (Reference).
-   To compare the study results with literature
    -   e.g., “The blood pressure (BP) was recorded 140/95 in a patient under a stress condition. In an earlier study, BP was reported 145/90 in a patient under the same stress condition” (Reference).
-   To explain the research outcomes logically
    -   e.g., “It was observed that ethanol concentration reached a plateau after a certain time. This might have happened for the exhaustion of soluble sugars over time” (Reference).

Knowledge that can be assumed as **general knowledge** for the target audience does not have to be referenced. For example: "climate change is a mayor threat to food systems".\
**Own statements, considerations and conclusions** (unless they refer to earlier, published material) do not have to contain references. They can be made explicitly recognizable as such to the reader with an active choice of words (examples: I / we propose … I / we assume, … I / we conclude …).

## Reference system and citation styles

The referencing of existing sources, whether in written contributions or oral presentations, is carried out through the systematic application of a **‘reference system’**. Paraphrased passages, direct quotations and other material (e.g. images) taken from third parties (or from your own earlier publications) are identified as such. In the case of protected material, appropriate permission must also be obtained for its use.

A reference system consists of a style that is consistently applied to the whole product, based on two elements [@zabed_qi_2022]:

1.  Citing the source material in the text
2.  Listing the full details of each source (usually at the end), so that it is easy to find. This list does not contain any entries that do not also appear within the text.

There exist numerous different reference styles. These are sometimes specified by a particular academic field, or by a particular publication format (e.g. a specific journal). Examples of reference styles that use the **"in-text name style”** are APA, Chicago or Harvard. Examples of reference styles that use the **"in-text numerical style"** are Vancouver, ACS or IEEE.

Unless explicitly stated otherwise by the lecturers, you are free to choose which citation style you would like to use in our degree program, but you are expected to transparently refer to third party work by referencing it and to apply the chosen reference style consistently across the whole publication. For each style, there are extensive rules on how to refer to sources in the text and how to present different types of sources.

::: {.callout-tip collapse="true"}
### Examples for reference styles

-   [APA reference style](https://apastyle.apa.org/style-grammar-guidelines/references/examples){target="_blank"}
-   [Vancouver reference style](https://library.viu.ca/citing/vancouver){target="_blank"}
:::

## Referencing Software Programs

The implementation of a coherent citation style is supported by the use of appropriate software apps. There are many such programmes, e.g. Zotero, Endnote, Citavi, Mendeley Referencing Manager, etc.

Most of these programmes not only support correct and coherent referencing but also serve as helpful reference management systems. We recommend that you use an app to manage and reference your literature. Again, you are free to choose, but we recommend [Zotero](https://www.zotero.org){target="_blank"}. On the one hand, Zotero is very user-friendly, on the other hand, you have unlimited storage space with the e-mail account of the University of Bern.

When writing with **LaTex** or **RMarkdown**, the formatting is done automatically. Here some further links:

-   [Zotero and LaTex](https://libguides.rhul.ac.uk/referencing/Zoterolatex){target="_blank"}
-   [Zotero and Jupyter Notebooks](https://pypi.org/project/jupyterlab-citation-manager/){target="_blank"}
-   [Zotero and RMarkdown](https://gsverhoeven.github.io/post/zotero-rmarkdown-csl/){target="_blank"}

## References in scientific presentatoins

The previous explanations can easily be realized in written texts. Please note that we also expect in **scientific presentations** (e.g. on Powerpoint slides) that knowledge taken from third parties is referenced, be it in the speech you give (e.g. "... previous findings of XY show that ...") and/or on the presented slides.

The same applies to images, figures or tables used from third parties. In order to keep the slides clear, citation styles that use a short form on the slide and a full list at the end of the presentation are particularly recommended.

## Referencing in non-scientific publications

Also, in texts and presentations targeting at a non-scientific audience, it is essential to acknowledge the knowledge used by third parties. However, such publications usually focus on the author's own findings and conclusions. This means that the embedding of one's own statements in the existing body of knowledge is less extensive and limited to key sources.

In addition, the choice of citation style can be used to try to disrupt the flow of reading as little as possible (e.g. with the in-text numerical style, or by underlaying text passages with hyperlinks that lead to the original source).

Last but not least, a text can become more comprehensible for a non-scientific audience if additional background information on the third party is provided when referring to statements and knowledge of third parties (e.g., “…. Maja Göpel, one of the most renowned transformation researchers in Germany, suggests in her work that …).

## Dive deeper into the topic

-   [Tutorials on the APA style](https://apastyle.apa.org/instructional-aids/tutorials-webinars){target="_blank"}
-   The [University Library of Bern](https://www.ub.unibe.ch/services/courses/reference_management_programs/index_eng.html){target="_blank"} offers support for reference management softwares.
-   [Quick start guide provided by Zotero](https://www.zotero.org/support/quick_start_guide){target="_blank"}
-   A bit more thorough guides to Zotero: [https://www.youtube.com/watch?v=tnbwKj6-pD8](https://www.youtube.com/watch?v=tnbwKj6-pD8){target="_blank"} or [https://www.youtube.com/watch?v=JG7Uq_JFDzE](https://www.youtube.com/watch?v=JG7Uq_JFDzE){target="_blank"}
-   [Information on copyright and licences](https://www.snf.ch/media/en/Ta5GhOd5M81J52oQ/Urheberrecht-Verlagsrecht-Lizenzen_Informationsblatt_EN.pdf){target="_blank"}
