project:
  type: book
  output-dir: docs
  resources: 
    - "*.png"
    - "*.jpeg"
    - "*.jfif"
    - "*.svg"

book:
  title: "Special course on inter- and transdisciplinary methods"
  subtitle: "Additional attainments for the Master's in Sustainability Transformations"
  favicon: images/
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  site-url: https://cdeteaching.github.io/SP_IDTDmethods/
 
  sidebar:
    search: true
    logo: images/cdelogo_e.png
    tools:
      - icon: file-earmark-pdf
        href: https://cdeteaching.github.io/SP_IDTDmethods/pdf/SP_IDTD.pdf
        text: "Course Script (PDF)"
    
  page-footer:
    border: true
    left: |
      "This a product of <a href="www.cde.unibe.ch/">![](/images/cdelogo_e.png){style='width: auto; height: 35px; padding-left: 10px; padding-right: 10px; margin-bottom:5px;'}</a>
    center: |
      
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>. This work is licensed under a [CC-BY-NC-ND 4.0 Int License](https://creativecommons.org/licenses/by-nc-nd/4.0/)

  
  
  chapters:
  - index.qmd
  - intro.qmd
  - 1_scientificKnowledge.qmd
  - 2_knowledgeTypes.qmd
  - 3_referecing.qmd
  - 4_integrityEthics.qmd
  - 5_IDTD.qmd
  - 6_methodsReflection.qmd
  - references.qmd

bibliography: references.bib

format:
  html:
    mainfont: Roboto
    monofont: Fira Code
    highlight-style: arrow
    monobackgroundcolor: "#F7F7F7"
    theme: 
    #  - theme.css
      - theme.scss
    callout-icon: false
  
  pdf:
  # render pdf to separate folder -> do it manually via terminal
  # "quarto render --to pdf --output SP_IDTD.pdf --output-dir pdf"
    documentclass: book
    mainfont: "Times New Roman"
    sansfont: "Arial"
    monofont: "Courier New"
    urlcolor: "blue"
    number-depth: 3
    papersize: a4
    fig-pos: "H"
    classoption: openany
    pdf-engine: xelatex
    metadata:
      title: "book"
    callout-icon: false  
    
    

editor: visual


